version: '3.7'
services:
  qbot_db:
    build: db
    container_name: qbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=qbot
      - POSTGRES_PASSWORD=qbot
      - POSTGRES_DB=qbot_db
    ports:
      - "5123:5432"
  qbot_redis:
    image: redis
    container_name: qbot_redis
    ports:
      - "6380:6379"
volumes:
  postgres_data: