# Generated by Django 3.0.7 on 2020-08-10 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_init', '0008_auto_20200808_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_csv', models.CharField(max_length=500)),
                ('name', models.CharField(choices=[('Kazan', 'Казань')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.CharField(choices=[('fajr', 'Иртәнге'), ('sunrise', 'Восход'), ('dhuhr', 'Өйлә'), ('asr', 'Икенде'), ('maghrib', 'Ахшам'), ("isha'a", 'Ястү')], max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.City')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.Day')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerAtUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerAtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.Prayer')),
                ('prayer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.PrayerAtUserGroup')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.Subscriber')),
            ],
        ),
    ]
