# Generated by Django 3.2.10 on 2022-01-02 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('prayer', '0001_initial'), ('prayer', '0002_auto_20200810_0924'), ('prayer', '0003_auto_20200810_1012'), ('prayer', '0004_auto_20200810_1557'), ('prayer', '0005_auto_20200810_1606'), ('prayer', '0006_auto_20200811_1852'), ('prayer', '0007_auto_20200823_0857'), ('prayer', '0008_alter_city_name'), ('prayer', '0009_auto_20220102_0426')]

    dependencies = [
        ('bot_init', '0011_auto_20200811_1852'),
        ('bot_init', '0008_auto_20200808_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_csv', models.CharField(max_length=500, verbose_name='Ссылка для скачивания csv файла с временами намазов')),
                ('name', models.CharField(max_length=200, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата намаза')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время намаза')),
                ('name', models.CharField(choices=[('fajr', 'Иртәнге'), ('sunrise', 'Восход'), ('dhuhr', 'Өйлә'), ('asr', 'Икенде'), ('maghrib', 'Ахшам'), ("isha'a", 'Ястү')], max_length=10, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.city', verbose_name='Город')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.day', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Время намаза',
                'verbose_name_plural': 'Времена намазов',
            },
        ),
        migrations.CreateModel(
            name='PrayerAtUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerAtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитан ли намаз')),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers_at_user', to='prayer.prayer', verbose_name='')),
                ('prayer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer.prayeratusergroup', verbose_name='Сгруппированные по 5 намазы для пользователя')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.subscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Запись о намазе для пользователя',
                'verbose_name_plural': 'Записи о намазе для пользователей',
            },
        ),
    ]
