# Generated by Django 4.0 on 2022-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_rename_link_to_csv_city_link_city_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayeratusergroup',
            options={'verbose_name': 'Группа времен намазов, привязанный к пользователю', 'verbose_name_plural': 'Группы времен намазов, привязанный к пользователю'},
        ),
    ]
