# Generated by Django 3.2.13 on 2022-08-25 12:05

import uuid

from django.db import migrations, models


def update_uuids(apps, schema_editor):
    City = apps.get_model('prayer.City')
    for city in City.objects.all():
        city.uuid = uuid.uuid4()
        city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0003_alter_prayeratusergroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(update_uuids),
    ]
