# Generated by Django 3.2.13 on 2022-08-29 18:44

from django.db import migrations, models
import uuid


def update_uuids(apps, schema_editor):
    PrayerAtUserGroup = apps.get_model('prayers.PrayerAtUserGroup')
    for prayer_at_user_group in PrayerAtUserGroup.objects.all():
        prayer_at_user_group.uuid = uuid.uuid4()
        prayer_at_user_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0004_city_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayeratusergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(update_uuids),
    ]
