version: "3.9"
   
services:
  qbot:
    build: .
    network_mode: "host"
    command: ddtrace-run gunicorn config.wsgi:application -c deploy/gunicorn.conf.py --reload
    ports:
      - "127.0.0.1:8000:8000"
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - BOT_TOKEN=452230948:AAFvAXqcuK8xhw1gfGnxlp6zzWQaR9qK7hw
    #   - SECRET_KEY=asdf
    #   - HOST=localhost
    #   - ADMINS=358610865
    #   - DEBUG=on
    #   - REDIS_CONNECTION=redis://localhost:6380/0
    #   - DATABASE_URL=psql://almazilaletdinov@192.168.0.1:5432/qbot_db

