[tool.poetry]
name = "quranbot"
version = "2.4.1"
description = ""
authors = ["Almaz <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.8"
pyTelegramBotAPI = "^4.1.1"
celery = "<5.0.0"
loguru = "^0.5.3"
django-split-settings = "^1.1.0"
django-environ = "^0.8.0"
ddtrace = "^0.56.0"
djangorestframework = "^3.12.4"
drf-yasg = "^1.20.0"
django-cors-headers = "^3.10.0"
psycopg2-binary = "^2.9.1"
geopy = "^2.2.0"
djangorestframework-simplejwt = "^5.0.0"
progressbar2 = "^3.55.0"
beautifulsoup4 = "^4.10.0"
lxml = "^4.6.3"
ipython = "^7.28.0"
gunicorn = "^20.1.0"
boto3 = "^1.18.63"
redis = "^4.0.0"
hiredis = "^2.0.0"
coreapi = "^2.3.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-django = "^4.4.0"
pytest-dotenv = "^0.5.2"
pytest-freezegun = "^0.4.2"
pytest-cov = "^3.0.0"
flake8 = "^3.9.2"
flake8-commas = "^2.0.0"
flake8-isort = "^4.0.0"
flake8-print = "^4.0.0"
pytest-xdist = "^2.4.0"
mixer = "^7.2.0"
requests-mock = "^1.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
