logs:

  - type: file
    path: /home/www/code/quranbot/logs/app.log
    service: qbot
    source: python
    sourcecategory: sourcecode

  - type: file
    path: /home/www/code/quranbot/logs/supervisor.log
    service: qbot_gunicorn
    source: gunicorn
    log_processing_rules:
      - type: multi_line
        name: log_start_with_date
        pattern: \[\d{4}-\d{2}-\d{2}

  - type: file
    path: /home/www/code/quranbot/logs/celery.log
    service: celery
    source: python
    sourcecategory: sourcecode
