# Generated by Django 3.2.10 on 2022-01-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя файла')),
                ('link_to_file', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('tg_file_id', models.CharField(blank=True, help_text='Может быть пустым, т. к. некоторые файлы слишком велики для отправки.', max_length=512, null=True, verbose_name='Идентификатор файла в телеграмм')),
            ],
        ),
        migrations.CreateModel(
            name='MorningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.TextField(blank=True, verbose_name='Дополнительный текст')),
                ('day', models.IntegerField(unique=True, verbose_name='День')),
            ],
            options={
                'verbose_name': 'Ежедневный контент для пользователей',
                'verbose_name_plural': 'Ежедневный контент для пользователей',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер суры')),
                ('pars_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш после предыдущей сессии парсинга')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка на суру')),
                ('child_elements_count', models.IntegerField(verbose_name='Кол-во записей аятов в суре')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('article_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на статью')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='content.file', verbose_name='Аудио файл')),
            ],
            options={
                'verbose_name': 'Аудио подкаст',
                'verbose_name_plural': 'Аудио подкасты',
            },
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.TextField(blank=True, verbose_name='Дополнительный контент')),
                ('content', models.TextField(blank=True, verbose_name='Текст аята')),
                ('arab_text', models.TextField(blank=True, verbose_name='Арабский текст')),
                ('trans', models.TextField(blank=True, verbose_name='Транслитерация')),
                ('ayat', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер аята')),
                ('html', models.TextField(verbose_name='Спарсенный HTML текст')),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.file', verbose_name='Аудио файл')),
                ('one_day_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.morningcontent', verbose_name='Ежедневный контент')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.sura', verbose_name='Номер суры')),
            ],
            options={
                'verbose_name': 'Аят Священного Корана',
                'verbose_name_plural': 'Аяты Священного Корана',
                'ordering': ['-id'],
            },
        ),
    ]
