# Generated by Django 3.2.10 on 2022-01-02 01:32

from django.db import migrations, models
import django.db.models.deletion

from apps.content.services.get_content_from_morning_content import get_content


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.content.migrations.0018_auto_20210711_1410
# TODO: move to services for reusing
def delete_too_many_len_content(apps, schema_editor):
    MorningContent = apps.get_model('content', 'MorningContent')
    for m in MorningContent.objects.all():
        if len(get_content(m.ayat_set.all(), m.additional_content)) > 4096:
            MorningContent.objects.filter(pk__gte=m.pk).delete()


def delete_morning_content_without_body(apps, schema_editor):
    MorningContent = apps.get_model('content', 'MorningContent')
    for m in MorningContent.objects.all():
        if m.ayat_set.count == 0:
            m.delete()

# 0011
def fill_suras(apps, schema_editor):
    links = ['/sura-1-al-fatiha-otkryvayushhaya/', '/sura-2-al-bakara-korova/', '/sura-3-alyu-imran-rod-imrana/', '/sura-4-an-nisa-zhenshhiny/', '/sura-5-al-maida-trapeza/', '/sura-6-al-an-am-skot/', '/sura-7-al-a-raf-pregrada/', '/sura-8-al-anfal-trofei/', '/sura-9-at-tavba-pokayanie/', '/sura-10-yunus-iona/', '/sura-11-hud-hud/', '/sura-12-prekrasnyj-yusuf-tselomudrennyj-iosif/', '/sura-13-ar-ra-d-grom/', '/sura-14-ibrahim-avraam/', '/sura-15-al-hidzhr-hidzhr/', '/sura-16-an-nahl-pchela/', '/sura-17-al-isra-perenesenie-nochyu/', '/sura-18-al-kyahf-peshhera/', '/sura-19-maryam-mariya/', '/sura-20-ta-ha-ta-ha/', '/sura-21-al-anbiya-proroki/', '/sura-22-al-hadzh-hadzh/', '/sura-23-al-mu-minun-veruyushhie/', '/sura-24-an-nur-svet/', '/sura-25-al-furkan-koran-razlichayushhij-dobro-i-zlo/', '/sura-26-ash-shu-ara-poety/', '/sura-27-an-naml-muravi/', '/sura-28-al-kasas-povestvovanie/', '/sura-29-al-ankyabut-pauk/', '/sura-30-ar-rum-rim/', '/sura-31-lukman-lukman/', '/sura-32-as-sadzhda-zemnoj-poklon/', '/sura-33-al-ahzab-soyuzniki/', '/sura-34-saba-saba/', '/sura-35-fatyr-tvorets/', '/sura-36-yasin-yasin/', '/sura-37-as-soffat-angely-stoyashhie-ryadami/', '/sura-38-sod-sod/', '/sura-39-az-zumar-gruppy/', '/sura-40-gafir-proshhayushhij/', '/sura-41-fussylyat-raskryty/', '/sura-42-ash-shura-sovet/', '/sura-43-az-zuhruf-ukrashenie/', '/sura-44-ad-duhan-dym/', '/sura-45-al-dzhasiya-vstavshaya-na-koleni/', '/sura-46-al-ahkaf-peschanye-holmy/', '/sura-47-muhammad-muhammad/', '/sura-48-al-fath-otkrytie/', '/sura-49-al-hudzhurat-komnaty/', '/sura-50-kaf-kaf/', '/sura-51-az-zariyat-unosyashhie-vetra/', '/sura-52-at-tur-gora-zarosshaya-derevyami/', '/sura-53-an-nadzhm-zvezda/', '/sura-54-al-kamar-luna/', '/sura-55-ar-rahman-vsemilostivyj/', '/sura-56-al-vaky-a-sobytie/', '/sura-57-al-hadid-zhelezo/', '/sura-58-al-mudzhadilya-dokazyvayushhaya-nastojchivo-dobivayushhayasya-svoego/', '/sura-59-al-hashr-sbor/', '/sura-60-al-mumtahana-ispytuemaya/', '/sura-61-as-soff-ryad/', '/sura-62-al-dzhum-a-pyatnitsa/', '/sura-63-al-munafikun-litsemery/', '/sura-64-at-tagabun-obmanulis/', '/sura-65-at-talak-razvod/', '/sura-66-at-tahrim-zapret/', '/sura-67-al-mulk-vlast/', '/sura-68-al-kalyam-pero/', '/sura-69-al-hakka-bedstvie/', '/sura-70-al-ma-aridzh-stupeni/', '/sura-71-nuh-noj/', '/sura-72-al-dzhinn-dzhinny/', '/sura-73-al-muzzammil-zakutavshijsya/', '/sura-74-al-muddassir-ukutavshijsya/', '/sura-75-al-kyyama-voskreshenie/', '/sura-76-al-insan-chelovek/', '/sura-77-al-mursalyat-otpravlyaemye/', '/sura-78-an-naba-vest/', '/sura-79-an-nazi-at-angely-vyryvayushhie-dushi-bezbozhnikov/', '/sura-80-abasa-nahmurilsya/', '/sura-81-at-takvir-vyklyuchenie-solntsa/', '/sura-82-al-infitor-raskol-neba/', '/sura-83-al-mutoffifin-obmanshhiki-v-torgovle/', '/sura-84-al-inshikak-raskol/', '/sura-85-al-burudzh-sozvezdiya/', '/sura-86-at-torik-yarkaya-zvezda/', '/sura-87-al-a-lya-prevyshe-vsego/', '/sura-88-al-gashiya-beda-kotoraya-nakroet-vse-i-vsya/', '/sura-89-al-fadzhr-rassvet/', '/sura-90-al-beled-gorod/', '/sura-91-ash-shams-solntse/', '/sura-92-al-lejl-noch/', '/sura-93-ad-duha-utro/', '/sura-94-ash-sharh-raskrytie/', '/sura-95-at-tin-smokovnitsy/', '/sura-96-al-alyak-sgustok-krovi/', '/sura-97-al-kadr-mogushhestvo/', '/sura-98-al-bejina-yavnoe-dokazatelstvo/', '/sura-99-az-zalzalya-zemletryasenie/', '/sura-100-al-adiyat-begushhie/', '/sura-101-al-kari-a-bedstvie/', '/sura-102-at-takyasur-priumnozhenie/', '/sura-103-al-asr-vek/', '/sura-104-al-humaza-klevetnik/', '/sura-105-al-fil-slon/', '/sura-106-kurajsh-kurajshity/', '/sura-107-al-ma-un-sosud/', '/sura-108-al-kyausar-kyausar/', '/sura-109-al-kyafirun-bezbozhniki/', '/sura-110-an-nasr-pomoshh/', '/sura-111-al-mased-palmovye-volokna/', '/sura-112-al-ihlyas-iskrennost/', '/sura-113-al-falyak-zarya/', '/sura-114-an-nas-lyudi/']
    sura_num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114]
    childs_count = [1, 275, 200, 176, 116, 165, 205, 75, 129, 108, 123, 98, 38, 51, 83, 127, 110, 107, 90, 116, 109, 76, 94, 60, 76, 208, 90, 87, 69, 57, 31, 30, 70, 52, 45, 67, 148, 66, 74, 83, 51, 53, 82, 45, 37, 34, 34, 29, 18, 41, 59, 47, 58, 55, 77, 79, 29, 22, 24, 11, 14, 11, 11, 18, 10, 12, 30, 45, 37, 34, 26, 16, 20, 50, 30, 30, 49, 32, 37, 27, 21, 17, 23, 18, 18, 17, 19, 26, 16, 18, 14, 17, 11, 7, 8, 17, 4, 8, 6, 8, 6, 8, 1, 5, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1]
    Sura = apps.get_model('content', 'Sura')
    for i in range(len(links)):
        Sura.objects.create(
            number=sura_num[i],
            link=links[i],
            child_elements_count=childs_count[i]
        )

class Migration(migrations.Migration):

    replaces = [('content', '0001_initial'), ('content', '0002_auto_20200802_2052'), ('content', '0003_auto_20200804_2057'), ('content', '0004_remove_podcast_is_flag'), ('content', '0005_auto_20200808_1831'), ('content', '0006_auto_20200808_1845'), ('content', '0007_auto_20200808_1917'), ('content', '0008_auto_20200814_1920'), ('content', '0009_auto_20200814_1944'), ('content', '0010_auto_20200903_1939'), ('content', '0011_auto_20200903_1939'), ('content', '0012_remove_ayat_link_to_source'), ('content', '0013_auto_20200903_2120'), ('content', '0014_auto_20201219_2027'), ('content', '0015_podcast_article_link'), ('content', '0016_auto_20210409_2022'), ('content', '0017_auto_20210409_2109'), ('content', '0018_auto_20210711_1410'), ('content', '0019_auto_20210711_1412'), ('content', '0020_auto_20211209_1546'), ('content', '0021_auto_20220102_0426')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_file', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('tg_file_id', models.CharField(blank=True, help_text='Может быть пустым, т. к. некоторые файлы слишком велики для отправки.', max_length=512, null=True, verbose_name='Идентификатор файла в телеграмм')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MorningContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.TextField(blank=True, verbose_name='Дополнительный текст')),
                ('day', models.IntegerField(verbose_name='День')),
            ],
            options={
                'verbose_name': 'Ежедневный контент для пользователей',
                'verbose_name_plural': 'Ежедневный контент для пользователей',
            },
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер суры')),
                ('pars_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш после предыдущей сессии парсинга')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка на суру')),
                ('child_elements_count', models.IntegerField(verbose_name='Кол-во записей аятов в суре')),
            ],
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.TextField(blank=True, verbose_name='Допопнительный контент')),
                ('arab_text', models.TextField(blank=True, verbose_name='Арабский текст')),
                ('trans', models.TextField(blank=True, verbose_name='Транслитерация')),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.sura', verbose_name='Номер суры')),
                ('ayat', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер аята')),
                ('html', models.TextField(verbose_name='Спарсенный HTML текст')),
                ('audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.file', verbose_name='Аудио файл')),
                ('one_day_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.morningcontent', verbose_name='Ежедневный контент')),
                ('content', models.TextField(blank=True, verbose_name='Текст аята')),
            ],
            options={
                'verbose_name': 'Аят Священного Корана',
                'verbose_name_plural': 'Аяты Священного Корана',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='content.file', verbose_name='Аудио файл')),
                ('article_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на статью')),
            ],
            options={
                'verbose_name': 'Аудио подкаст',
                'verbose_name_plural': 'Аудио подкасты',
            },
        ),
        migrations.RunPython(
            delete_morning_content_without_body,
        ),
        migrations.RunPython(
            delete_too_many_len_content,
        ),
        migrations.AlterModelOptions(
            name='ayat',
            options={'ordering': ['-id'], 'verbose_name': 'Аят Священного Корана', 'verbose_name_plural': 'Аяты Священного Корана'},
        ),
        migrations.AlterModelOptions(
            name='morningcontent',
            options={'ordering': ['-day'], 'verbose_name': 'Ежедневный контент для пользователей', 'verbose_name_plural': 'Ежедневный контент для пользователей'},
        ),
        migrations.AlterField(
            model_name='morningcontent',
            name='day',
            field=models.IntegerField(unique=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='ayat',
            name='additional_content',
            field=models.TextField(blank=True, verbose_name='Дополнительный контент'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='ayat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='morningcontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # migrations.RunPython(fill_suras),
    ]
