# Generated by Django 4.0 on 2022-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial_squashed_0021_auto_20220102_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='sura',
            options={'verbose_name': 'Сура', 'verbose_name_plural': 'Суры'},
        ),
    ]
