# Generated by Django 3.2.13 on 2022-08-25 08:40

from django.db import migrations, models
import uuid


def update_uuids(apps, schema_editor):
    File = apps.get_model('content.File')
    for file in File.objects.all():
        file.uuid = uuid.uuid4()
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_file_options_alter_sura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(update_uuids),
    ]
