# Generated by Django 3.0.7 on 2020-08-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200804_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='is_flag',
        ),
    ]
