# Generated by Django 3.0.7 on 2020-08-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200808_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.AudioFile', verbose_name='Аудио файл'),
        ),
    ]
