# Generated by Django 3.0.7 on 2020-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200814_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='ayat',
            field=models.CharField(max_length=16, null=True, verbose_name='Номер аята'),
        ),
        migrations.AlterField(
            model_name='ayat',
            name='sura',
            field=models.IntegerField(null=True, verbose_name='Номер суры'),
        ),
    ]
