# Generated by Django 3.1.4 on 2020-12-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20200903_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='ayat',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер аята'),
        ),
    ]
