# Generated by Django 3.1.6 on 2021-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20201219_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='article_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на статью'),
        ),
    ]
