# Generated by Django 3.1.6 on 2021-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20201219_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='flag_for_parser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
