# Generated by Django 3.1.7 on 2021-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_podcast_article_link'),
    ]

    operations = [
        migrations.RenameModel('AudioFile', 'File'),
        migrations.RenameField('File', 'audio_link', 'link_to_file'),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='tg_file_id',
            field=models.CharField(blank=True, help_text='Может быть пустым, т. к. некоторые файлы слишком велики для отправки.', max_length=512, null=True, verbose_name='Идентификатор файла в телеграмм'),
        ),
    ]
