# Generated by Django 3.1.7 on 2021-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210409_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link_to_file',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
