# Generated by Django 3.1.7 on 2021-04-09 18:24

from django.db import migrations


def create_document(apps, schema_editor):
    File = apps.get_model("content", "File")
    File.objects.create(
        name="PDF_ramadan_dairy",
        tg_file_id="BQACAgIAAxkDAAEBOktgb0-4obKhQY4G933tcwaaASE8XwAChQ0AAoXVeUs1xoB_m1sYbx4E",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210409_2109'),
    ]

    operations = [
        migrations.RunPython(create_document)
    ]
