# Generated by Django 3.2.4 on 2021-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210711_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayat',
            options={'ordering': ['-id'], 'verbose_name': 'Аят Священного Корана', 'verbose_name_plural': 'Аяты Священного Корана'},
        ),
        migrations.AlterModelOptions(
            name='morningcontent',
            options={'ordering': ['-day'], 'verbose_name': 'Ежедневный контент для пользователей', 'verbose_name_plural': 'Ежедневный контент для пользователей'},
        ),
        migrations.AlterField(
            model_name='morningcontent',
            name='day',
            field=models.IntegerField(unique=True, verbose_name='День'),
        ),
    ]
