# Generated by Django 3.2.10 on 2021-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210711_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='additional_content',
            field=models.TextField(blank=True, verbose_name='Дополнительный контент'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя файла'),
        ),
    ]
