# Generated by Django 3.0.7 on 2020-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0014_auto_20200814_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_unknown',
            field=models.BooleanField(default=False, verbose_name='Необработанное ли это сообщение'),
        ),
    ]
