# Generated by Django 3.0.9 on 2020-08-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0015_message_is_unknown'),
        ('bot_init', '0014_auto_20200822_2213'),
    ]

    operations = [
    ]
