# Generated by Django 3.0.9 on 2020-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0017_auto_20200903_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='step',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Шаг пользователя'),
        ),
    ]
