# Generated by Django 3.0.7 on 2020-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_auto_20200810_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('kazan', 'Казань')], max_length=200),
        ),
    ]
