# Generated by Django 3.2.10 on 2022-01-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ, по которому сообщение вызывается в коде')),
            ],
            options={
                'verbose_name': 'Административное сообщение',
                'verbose_name_plural': 'Административные сообщения',
            },
        ),
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('call_id', models.CharField(max_length=500, verbose_name='Идентификатор данных')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата из которого пришли данные')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'Данные с inline кнопок',
                'verbose_name_plural': 'Данные с inline кнопок',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('from_user_id', models.IntegerField(verbose_name='Идентификатор отправителя')),
                ('message_id', models.IntegerField(verbose_name='Идентификатор сообщения')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата, в котором идет общение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
                ('is_unknown', models.BooleanField(default=False, verbose_name='Необработанное ли это сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-message_id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор подписчика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписан ли пользователь на бота')),
                ('step', models.CharField(blank=True, max_length=100, null=True, verbose_name='Шаг пользователя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к подписчику')),
                ('day', models.IntegerField(default=2, verbose_name='День, для рассылки утреннего контента')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='SubscriberAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('action', models.CharField(choices=[('subscribed', 'подписался'), ('unsubscribed', 'отписался'), ('reactivated', 'реактивировался')], max_length=16, verbose_name='Действие')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.subscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Действия пользователя',
                'verbose_name_plural': 'Действия пользователей',
            },
        ),
    ]
