# Generated by Django 3.2.10 on 2022-01-02 01:36

import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.bot_init.migrations.0017_auto_20200903_2133
def create_start_admin_message(apps, schema_editor):
    AdminMessage = apps.get_model('bot_init', 'AdminMessage')
    AdminMessage.objects.create(title='start', key='start', text='Этот бот поможет тебе изучить Коран по богословскому переводу Шамиля Аляутдинова.\n\nКаждое утро, вам будут приходить аяты из Священного Корана.\n\nПри нажатии на кнопку Подкасты, вам будут присылаться проповеди с сайта umma.ru.\n\nТакже вы можете отправите номер суры, аята (например <b>4:7</b>) и получить: аят в оригинале, перевод на русский язык, транслитерацию и аудио')


# apps.bot_init.migrations.0021_auto_20210402_1107
def create_concourse_admin_message(apps, schema_editor):
    AdminMessage = apps.get_model('bot_init', 'AdminMessage')

    AdminMessage.objects.create(
        text=""" 💥Розыгрыш💥

Наступает священный месяц Рамадан и я хочу разыграть среди своих пользователей бота 3 дневника помощника📿

Этот дневник вы могли увидеть на Инстаграмм-странице моей жены <a href='https://www.instagram.com/a.agush/'>a.agush</a>

Такого дневника НИГДЕ нет, это ограниченный товар, его нигде нельзя купить. Поэтому у вас есть возможность выиграть его для себя или своей жены/сестры/подруги.

 Условия:

1️⃣ Быть подписчиком бота @Quran_365_bot
2️⃣ Получить реферальную ссылку, нажав на кнопку «»
3️⃣ Пригласить как минимум 1 друга подписаться на @Quran_365_bot по своей реферальной ссылке.

Результаты узнаем 8 апреля в 20:00 по МСК с помощью рандомайзера🎲

Участвуют все города России, доставка за мой счёт🚛 """,
        key='concourse',
    )


class Migration(migrations.Migration):

    replaces = [('bot_init', '0001_initial'), ('bot_init', '0002_auto_20200729_0103'), ('bot_init', '0003_auto_20200729_0106'), ('bot_init', '0004_subscriberaction'), ('bot_init', '0005_auto_20200729_0234'), ('bot_init', '0006_auto_20200802_2052'), ('bot_init', '0007_auto_20200805_0127'), ('bot_init', '0008_auto_20200808_2057'), ('bot_init', '0009_subscriber_city'), ('bot_init', '0010_auto_20200810_1016'), ('bot_init', '0011_auto_20200811_1852'), ('bot_init', '0012_auto_20200811_2313'), ('bot_init', '0013_auto_20200812_0932'), ('bot_init', '0014_auto_20200814_1941'), ('bot_init', '0015_message_is_unknown'), ('bot_init', '0014_auto_20200822_2213'), ('bot_init', '0016_merge_20200822_2215'), ('bot_init', '0017_auto_20200903_2133'), ('bot_init', '0018_subscriber_step'), ('bot_init', '0019_auto_20201219_2027'), ('bot_init', '0020_subscriber_referer'), ('bot_init', '0021_auto_20210402_1107'), ('bot_init', '0022_alter_message_options'), ('bot_init', '0023_auto_20211209_1546'), ('bot_init', '0024_auto_20220102_0337'), ('bot_init', '0025_auto_20220102_0426')]

    dependencies = [
        ('content', '0007_auto_20200808_1917'),
        ('content', '0002_auto_20200802_2052'),
        # ('prayer', '0003_auto_20200810_1012'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор подписчика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписан ли польователь на бота')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к подписчику')),
                ('day', models.IntegerField(default=2, verbose_name='День, для рассылки утреннего контента')),
                ('favourite_ayats', models.ManyToManyField(blank=True, related_name='favorit_ayats', to='content.Ayat', verbose_name='Избранные аяты')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Навзвание')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ, по которому сообщение вызывается в коде')),
            ],
            options={
                'verbose_name': 'Админитративное сообщение',
                'verbose_name_plural': 'Админитративное сообщения',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_init.subscriber')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('call_id', models.CharField(max_length=500, verbose_name='Идентификатор данных')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата из которого пришли данные')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'Данные с inline кнопок',
                'verbose_name_plural': 'Данные с inline кнопок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('from_user_id', models.IntegerField(verbose_name='Идентификатор отправителя')),
                ('message_id', models.IntegerField(verbose_name='Идентификатор сообщения')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата, в котором идет общение')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='bot_init.mailing')),
                ('is_unknown', models.BooleanField(default=False, verbose_name='Необработанное ли это сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SubscriberAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('action', models.CharField(choices=[('subscribed', 'подписался'), ('unsubscribed', 'отписался'), ('reactivated', 'реактивировался')], max_length=16, verbose_name='Действие')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.subscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Действия пользователя',
                'verbose_name_plural': 'Действия пользователей',
            },
        ),
        migrations.RunPython(
            create_start_admin_message,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='step',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Шаг пользователя'),
        ),
        migrations.AlterField(
            model_name='callbackdata',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_init.subscriber', verbose_name='Реферер подписчика'),
        ),
        migrations.RunPython(
            create_concourse_admin_message,
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='adminmessage',
            options={'verbose_name': 'Административное сообщение', 'verbose_name_plural': 'Административные сообщения'},
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписан ли пользователь на бота'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='callbackdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriberaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
