# Generated by Django 3.2.10 on 2022-01-02 01:42

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0001_initial_squashed_0025_auto_20220102_0426'),
        ('prayer', '0001_initial_squashed_0009_auto_20220102_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prayer.city', verbose_name='Город для рассылки намазов'),
        )
    ]
