# Generated by Django 3.0.7 on 2020-07-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('bot_init', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('key', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Админитративное сообщение',
                'verbose_name_plural': 'Админитративное сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='favorit_ayats',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorit_ayats', to='content.Ayat'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписан ли польователь на бота'),
        ),
        migrations.AddField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot_init.Mailing'),
        ),
    ]
