# Generated by Django 3.2.10 on 2022-01-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prayer', '0001_initial'),
        ('bot_init', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prayer.city', verbose_name='Город для рассылки намазов'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='favourite_ayats',
            field=models.ManyToManyField(blank=True, related_name='favorit_ayats', to='content.Ayat', verbose_name='Избранные аяты'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_init.subscriber', verbose_name='Реферер подписчика'),
        ),
        migrations.AddField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='bot_init.mailing'),
        ),
        migrations.AddField(
            model_name='admin',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_init.subscriber'),
        ),
    ]
