# Generated by Django 4.0 on 2022-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0002_auto_20220102_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_cleaned',
            field=models.BooleanField(default=False, verbose_name='Очищены ли сообщения из этой рассылки у пользователей'),
        ),
    ]
