# Generated by Django 4.0 on 2022-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0002_auto_20220102_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор сообщения'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='tg_chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор подписчика'),
        ),
    ]
