# Generated by Django 3.0.7 on 2020-07-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0003_auto_20200729_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('subscribed', 'подписался'), ('unsubscribed', 'отписался'), ('reactivated', 'реактивировался')], max_length=16)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_init.Subscriber')),
            ],
        ),
    ]
