# Generated by Django 4.0 on 2022-08-08 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0003_mailing_is_cleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания уведомления')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Уведомление прочитано')),
                ('readed_at', models.DateTimeField(null=True, verbose_name='Время прочтения уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
            },
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-id'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
