# Generated by Django 4.0 on 2022-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0004_notification_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='tg_chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Идентификатор подписчика'),
        ),
    ]
