# Generated by Django 4.0 on 2022-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0005_alter_subscriber_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackdata',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Идентификатор чата из которого пришли данные'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Идентификатор чата, в котором идет общение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user_id',
            field=models.BigIntegerField(verbose_name='Идентификатор отправителя'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(verbose_name='Идентификатор сообщения'),
        ),
    ]
