# Generated by Django 3.0.7 on 2020-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200802_2052'),
        ('bot_init', '0005_auto_20200729_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriberaction',
            options={'verbose_name': 'Действия пользователя', 'verbose_name_plural': 'Действия пользователей'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='favorit_ayats',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='favourite_ayats',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorit_ayats', to='content.Ayat', verbose_name='Избранные аяты'),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='key',
            field=models.CharField(max_length=128, verbose_name='Ключ, по которому сообщение вызывается в коде'),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Навзвание'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий к подписчику'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='day',
            field=models.IntegerField(default=2, verbose_name='День, для рассылки утреннего контента'),
        ),
    ]
