# Generated by Django 3.0.7 on 2020-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200808_1917'),
        ('bot_init', '0010_auto_20200810_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('call_id', models.IntegerField(verbose_name='Идентификатор данных')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата из которого пришли данные')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'Данные с inline кнопок',
                'verbose_name_plural': 'Данные с inline кнопок',
            },
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='favourite_ayats',
            field=models.ManyToManyField(blank=True, related_name='favorit_ayats', to='content.Ayat', verbose_name='Избранные аяты'),
        ),
    ]
