# Generated by Django 3.0.7 on 2020-08-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0011_auto_20200811_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackdata',
            name='call_id',
            field=models.CharField(max_length=500, verbose_name='Идентификатор данных'),
        ),
    ]
