# Generated by Django 3.0.7 on 2020-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0012_auto_20200811_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='tg_chat_id',
            field=models.IntegerField(unique=True, verbose_name='Идентификатор подписчика'),
        ),
    ]
