# Generated by Django 3.0.7 on 2020-09-03 18:33

from django.db import migrations


def create_start_admin_message(apps, schema_editor):
    AdminMessage = apps.get_model('bot_init', 'AdminMessage')
    AdminMessage.objects.create(title='start', key='start', text='Этот бот поможет тебе изучить Коран по богословскому переводу Шамиля Аляутдинова.\n\nКаждое утро, вам будут приходить аяты из Священного Корана.\n\nПри нажатии на кнопку Подкасты, вам будут присылаться проповеди с сайта umma.ru.\n\nТакже вы можете отправите номер суры, аята (например <b>4:7</b>) и получить: аят в оригинале, перевод на русский язык, транслитерацию и аудио')


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0016_merge_20200822_2215'),
    ]

    operations = [
        migrations.RunPython(create_start_admin_message)
    ]
