# Generated by Django 3.1.4 on 2020-12-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0018_subscriber_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackdata',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
