# Generated by Django 3.1.7 on 2021-04-02 08:07

from django.db import migrations


def create_concourse_admin_message(apps, schema_editor):
    AdminMessage = apps.get_model("bot_init", "AdminMessage")

    AdminMessage.objects.create(
        text="some message",
        key="concourse",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0020_subscriber_referer'),
    ]

    operations = [
        migrations.RunPython(create_concourse_admin_message)
    ]
