# Generated by Django 3.2 on 2021-05-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0021_auto_20210402_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
