# Generated by Django 3.2 on 2021-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0021_auto_20210402_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Коммент сообщения'),
        ),
    ]
