# Generated by Django 3.2.10 on 2021-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0022_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessage',
            options={'verbose_name': 'Административное сообщение', 'verbose_name_plural': 'Административные сообщения'},
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписан ли пользователь на бота'),
        ),
    ]
