# Generated by Django 3.2.6 on 2021-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0022_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_cleaned',
            field=models.BooleanField(default=False, verbose_name='Очищены ли сообщения из этой рассылки у пользователей'),
        ),
    ]
