# Generated by Django 3.0.7 on 2020-08-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200802_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='tg_audio_link',
            new_name='tg_file_id',
        ),
    ]
