# Generated by Django 3.0.7 on 2020-08-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200808_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='tg_file_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Идентификатор файла в телеграмм'),
        ),
    ]
