# Generated by Django 3.0.9 on 2020-09-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200814_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('pars_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('link', models.CharField(max_length=128)),
                ('child_elements_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ayat',
            name='sura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.Sura', verbose_name='Номер суры'),
            preserve_default=False,
        ),
    ]
