# Generated by Django 3.0.9 on 2020-09-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200903_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayat',
            name='link_to_source',
        ),
    ]
