# Generated by Django 3.0.7 on 2020-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_ayat_link_to_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sura',
            name='child_elements_count',
            field=models.IntegerField(verbose_name='Кол-во записей аятов в суре'),
        ),
        migrations.AlterField(
            model_name='sura',
            name='link',
            field=models.CharField(max_length=128, verbose_name='Ссылка на суру'),
        ),
        migrations.AlterField(
            model_name='sura',
            name='number',
            field=models.IntegerField(verbose_name='Номер суры'),
        ),
        migrations.AlterField(
            model_name='sura',
            name='pars_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш после предыдущей сессии парсинга'),
        ),
    ]
